FROM maven:3.9-eclipse-temurin-11-alpine AS build

WORKDIR /app

COPY pom.xml ./
COPY src ./src

RUN mvn clean package -DskipTests

############################################
FROM eclipse-temurin:11-jre-alpine
LABEL maintainer="Thiago Santana"

WORKDIR /app

COPY --from=build /app/target/javalin-app.jar app.jar
EXPOSE 7070 

CMD ["java", "-jar", "app.jar"]